version: '3'

volumes:
  web:
  db:

networks:
  internal:

services:
  db:
    image: postgres:13-alpine
    networks:
      - internal
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - 5432
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks:
      - internal
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
